package com.wookii.simpletalk.greenrobot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table table_friend.
 */
public class Friend {

    private Long id;
    /** Not-null value. */
    private String friend_id;
    private String friend_name;
    private String friend_remark;
    private String friend_user_name;
    private String friend_url;
    private String friend_gender;
    private String friend_last_words;

    public Friend() {
    }

    public Friend(Long id) {
        this.id = id;
    }

    public Friend(Long id, String friend_id, String friend_name, String friend_remark, String friend_user_name, String friend_url, String friend_gender, String friend_last_words) {
        this.id = id;
        this.friend_id = friend_id;
        this.friend_name = friend_name;
        this.friend_remark = friend_remark;
        this.friend_user_name = friend_user_name;
        this.friend_url = friend_url;
        this.friend_gender = friend_gender;
        this.friend_last_words = friend_last_words;
    }
    
    public Friend(String friend_id, String friend_name, String friend_remark, String friend_user_name, String friend_url, String friend_gender, String friend_last_words) {
        this.friend_id = friend_id;
        this.friend_name = friend_name;
        this.friend_remark = friend_remark;
        this.friend_user_name = friend_user_name;
        this.friend_url = friend_url;
        this.friend_gender = friend_gender;
        this.friend_last_words = friend_last_words;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFriend_id() {
        return friend_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFriend_id(String friend_id) {
        this.friend_id = friend_id;
    }

    public String getFriend_name() {
        return friend_name;
    }

    public void setFriend_name(String friend_name) {
        this.friend_name = friend_name;
    }

    public String getFriend_remark() {
        return friend_remark;
    }

    public void setFriend_remark(String friend_remark) {
        this.friend_remark = friend_remark;
    }

    public String getFriend_user_name() {
        return friend_user_name;
    }

    public void setFriend_user_name(String friend_user_name) {
        this.friend_user_name = friend_user_name;
    }

    public String getFriend_url() {
        return friend_url;
    }

    public void setFriend_url(String friend_url) {
        this.friend_url = friend_url;
    }

    public String getFriend_gender() {
        return friend_gender;
    }

    public void setFriend_gender(String friend_gender) {
        this.friend_gender = friend_gender;
    }

    public String getFriend_last_words() {
        return friend_last_words;
    }

    public void setFriend_last_words(String friend_last_words) {
        this.friend_last_words = friend_last_words;
    }

}
