package com.wookii.simpletalk.greenrobot;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.wookii.simpletalk.greenrobot.Friend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table table_friend.
*/
public class FriendDao extends AbstractDao<Friend, Long> {

    public static final String TABLENAME = "table_friend";

    /**
     * Properties of entity Friend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Friend_id = new Property(1, String.class, "friend_id", false, "FRIEND_ID");
        public final static Property Friend_name = new Property(2, String.class, "friend_name", false, "FRIEND_NAME");
        public final static Property Friend_remark = new Property(3, String.class, "friend_remark", false, "FRIEND_REMARK");
        public final static Property Friend_user_name = new Property(4, String.class, "friend_user_name", false, "FRIEND_USER_NAME");
        public final static Property Friend_url = new Property(5, String.class, "friend_url", false, "FRIEND_URL");
        public final static Property Friend_gender = new Property(6, String.class, "friend_gender", false, "FRIEND_GENDER");
        public final static Property Friend_last_words = new Property(7, String.class, "friend_last_words", false, "FRIEND_LAST_WORDS");
    };


    public FriendDao(DaoConfig config) {
        super(config);
    }
    
    public FriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'table_friend' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'FRIEND_ID' TEXT NOT NULL ," + // 1: friend_id
                "'FRIEND_NAME' TEXT," + // 2: friend_name
                "'FRIEND_REMARK' TEXT," + // 3: friend_remark
                "'FRIEND_USER_NAME' TEXT," + // 4: friend_user_name
                "'FRIEND_URL' TEXT," + // 5: friend_url
                "'FRIEND_GENDER' TEXT," + // 6: friend_gender
                "'FRIEND_LAST_WORDS' TEXT);"); // 7: friend_last_words
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'table_friend'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Friend entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFriend_id());
 
        String friend_name = entity.getFriend_name();
        if (friend_name != null) {
            stmt.bindString(3, friend_name);
        }
 
        String friend_remark = entity.getFriend_remark();
        if (friend_remark != null) {
            stmt.bindString(4, friend_remark);
        }
 
        String friend_user_name = entity.getFriend_user_name();
        if (friend_user_name != null) {
            stmt.bindString(5, friend_user_name);
        }
 
        String friend_url = entity.getFriend_url();
        if (friend_url != null) {
            stmt.bindString(6, friend_url);
        }
 
        String friend_gender = entity.getFriend_gender();
        if (friend_gender != null) {
            stmt.bindString(7, friend_gender);
        }
 
        String friend_last_words = entity.getFriend_last_words();
        if (friend_last_words != null) {
            stmt.bindString(8, friend_last_words);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Friend readEntity(Cursor cursor, int offset) {
        Friend entity = new Friend( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // friend_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // friend_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // friend_remark
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // friend_user_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // friend_url
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // friend_gender
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // friend_last_words
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Friend entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFriend_id(cursor.getString(offset + 1));
        entity.setFriend_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFriend_remark(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFriend_user_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFriend_url(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFriend_gender(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFriend_last_words(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Friend entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Friend entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
